### ISSUE TITLE
How to create pooled Normal bam? samtools merge?

### ISSUE THREAD

**Issue by 1512474508** [rptashkin/facets2n#21] opened 2020-06-17 05:52 UTC
unmatched-normal-BAMS "<some/path>/PoolNormal.bam"

**Comment by rptashkin** [comment] 2020-06-17 12:11
hi @1512474508, closing this as a duplicate of https://github.com/rptashkin/facets2n/issues/20. Do you have an additional question about this option?

**Closed by rptashkin** 2020-06-17 12:11 UTC
